### ISSUE TITLE
Ollama started service successfully but browser did not respond

### ISSUE THREAD

**Issue by su-zelong** [andrewnguonly/Lumos#13]
First of all thank you for your excellent work, but I have found some issues with my local deployment. My docker backend has successfully pulled up the local model service. In the command line curl access works fine, but when I set the OLLAMA_BASE_URL and OLLAMA_MODEL in script/background.ts the plugin is not responding in the browser.

My specific process is to use ollama inside docker for local model packaging, outside docker using curl access there is normal return, but after setting two parameters in the plugin there is no response from the plugin inside the browser.

**Comment by andrewnguonly** [comment]
@su-zelong, I suspect the issue is related to CORS security, which means the `OLLAMA_ORIGINS` environment variable needs to be set when running the Docker container. The [default instructions](https://hub.docker.com/r/ollama/ollama) for running the container do not specify this.

Run this command to run the container and set the `OLLAMA_ORIGINS` environment variable:
```
docker run -e OLLAMA_ORIGINS="chrome-extension://*" -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
```

If you have Docker Desktop, you can see that the `OLLAMA_ORIGINS` environment variable is set.

![image](https://github.com/andrewnguonly/Lumos/assets/7654246/bf3044e7-71b1-469c-8113-89ecd5706e6f)

Now, update the host address in `OLLAMA_BASE_URL` to `0.0.0.0` and rebuild the extension (`npm run build`):
```javascript
const OLLAMA_BASE_URL = "http://0.0.0.0:11434";
```

After following these steps, the Chrome extension successfully calls the Ollama API served from the Docker container. I'll update the `README` with these instructions.

**Comment by su-zelong** [comment]
Hello, I followed the command you gave to create the container and would like to call the local model (codellama)
The method I used to create the container:

docker run -itd -e OLLAMA_ORIGINS='chrome-extension://*' -p 11434:11434 --name ollama ollama/ollama

‘-itd’ because I want to deploy the local codellama in the plugin, then I go into the container and 
‘ollama create codellama ModelFile’ ,
 so that later I can access the local model externally via curl on port 11434, but still no response when I put the full url in the plugin

I try to use ‘ollama serve’ in the container but it comes up with

127.0.0.1:11434: bind: address already in use

**Comment by andrewnguonly** [comment]
@su-zelong 
> I try to use ‘ollama serve’ in the container but it comes up with
>
> 127.0.0.1:11434: bind: address already in use

You won't be able to run `ollama serve` from inside the container because the container is already configured to run `ollama serve` at startup, which means the Ollama host (e.g. `127.0.0.1`) is already used (bound) by another process. See the Dockerfile entry point configuration: https://github.com/jmorganca/ollama/blob/main/Dockerfile#L28C1-L29

> ‘-itd’ because I want to deploy the local codellama in the plugin, then I go into the container and
‘ollama create codellama ModelFile’ ,

Once the custom model is created, it doesn't seem like there's a way to restart the `ollama serve` process (see this issue: https://github.com/jmorganca/ollama/issues/1266). If you want to create a custom `Modelfile` and have the custom model served from the API in the container, you may have to create your own `Dockerfile` and `COPY` your custom `Modelfile`s into the image.

Alternatively, you can [create the custom model via the API](https://github.com/jmorganca/ollama/blob/main/docs/api.md#create-a-model) after the container is running. This approach worked for me. I was able to create a custom model and call it from outside the container. High level steps:
1. Run container: `docker run`
1. Create custom model (from outside container)
    ```
    curl http://0.0.0.0:11434/api/create -d '{
        "name": "Mario",
        "modelfile": "FROM llama2\nSYSTEM You are mario from Super Mario Bros."
    }'
    ```
1. Call custom model (from outside container)
    ```
    curl http://0.0.0.0:11434/api/chat -d '{
        "model": "Mario",
        "messages": [
            {
                "role": "user",
                "content": "why is the sky blue?"
            }
        ]
    }'
    ```
At this point, the Chrome extension should be able to call the custom model from outside the container.

**Comment by su-zelong** [comment]
@andrewnguonly 

Thank you very much for your itemized response to my question. I understand the reason why starting the container and ollama serve causes the port to be occupied; however, outside the container curl ... /api/create seems to have the same effect as ollama create inside the container. I also have normal access to 11434 under this method but still no response in the plugin. Next I'll try changing the dockerfile and re-pulling the image to try this. Also may I ask why so many plugins are based on the ollama interface? Why not use openai type interfaces like vllm or fastchat wouldn't they be more versatile. Again, thanks for the pointers!

**Comment by andrewnguonly** [comment]
@su-zelong, please open a new issue if you're still unable to connect to a custom model running in the Docker container. Thanks.
